# Site settings
title: Svti 的个人博客
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: https://svti.github.io
description: "云计算/大数据/搜索引擎/机器学习"
baseurl: "/svti.github.io"
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  Svti
facebook_username:  IronSummitMedia
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
